<template>
  <div
    :class="[
      'ha-animation-scale-up',
      variantClass,
      { 'is-active': isActive },
    ]"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
type Variant
  = | 'center'
    | 'top'
    | 'tr'
    | 'right'
    | 'br'
    | 'bottom'
    | 'bl'
    | 'left'
    | 'tl'
    | 'hor-center'
    | 'hor-left'
    | 'hor-right'
    | 'ver-center'
    | 'ver-top'
    | 'ver-bottom'

interface Props {
  /**
   * アニメーションの起点となる方向
   * @default 'center'
   */
  variant?: Variant
  /**
   * アニメーションをアクティブにするかどうか
   * @default false
   */
  active?: boolean
  /**
   * アニメーションの実行時間（秒）
   * @default 0.4
   */
  duration?: number
  /**
   * アニメーションの遅延時間（秒）
   * @default 0
   */
  delay?: number
  /**
   * アニメーションを無限にループするかどうか
   * @default false
   */
  infinite?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'center',
  active: false,
  duration: 0.4,
  delay: 0,
  infinite: false,
})

const isActive = ref(props.active)

const variantClass = computed(() => `-${props.variant}`)

// activeプロパティの変更を監視
watch(() => props.active, (newValue) => {
  isActive.value = newValue
})

// マウント時にactiveがtrueの場合、アニメーションを開始
onMounted(() => {
  if (props.active) {
    isActive.value = true
  }
})
</script>

<style lang="scss" scoped>
.ha-animation-scale-up {
  display: inline-block;

  &.is-active {
    &.-center {
      animation: scale-up-center v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-top {
      animation: scale-up-top v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-tr {
      animation: scale-up-tr v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-right {
      animation: scale-up-right v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-br {
      animation: scale-up-br v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-bottom {
      animation: scale-up-bottom v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-bl {
      animation: scale-up-bl v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-left {
      animation: scale-up-left v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-tl {
      animation: scale-up-tl v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-hor-center {
      animation: scale-up-hor-center v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-hor-left {
      animation: scale-up-hor-left v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-hor-right {
      animation: scale-up-hor-right v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-ver-center {
      animation: scale-up-ver-center v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-ver-top {
      animation: scale-up-ver-top v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }

    &.-ver-bottom {
      animation: scale-up-ver-bottom v-bind('`${duration}s`') cubic-bezier(0.390, 0.575, 0.565, 1.000) v-bind('`${delay}s`') v-bind('infinite ? "infinite" : "1"') normal both;
    }
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2025-10-16 17:38:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

// Center
@keyframes scale-up-center {
  0% {
    transform: scale(0.5);
  }

  100% {
    transform: scale(1);
  }
}

// Top
@keyframes scale-up-top {
  0% {
    transform-origin: 50% 0%;
    transform: scale(0.5);
  }

  100% {
    transform-origin: 50% 0%;
    transform: scale(1);
  }
}

// Top Right
@keyframes scale-up-tr {
  0% {
    transform-origin: 100% 0%;
    transform: scale(0.5);
  }

  100% {
    transform-origin: 100% 0%;
    transform: scale(1);
  }
}

// Right
@keyframes scale-up-right {
  0% {
    transform-origin: 100% 50%;
    transform: scale(0.5);
  }

  100% {
    transform-origin: 100% 50%;
    transform: scale(1);
  }
}

// Bottom Right
@keyframes scale-up-br {
  0% {
    transform-origin: 100% 100%;
    transform: scale(0.5);
  }

  100% {
    transform-origin: 100% 100%;
    transform: scale(1);
  }
}

// Bottom
@keyframes scale-up-bottom {
  0% {
    transform-origin: 50% 100%;
    transform: scale(0.5);
  }

  100% {
    transform-origin: 50% 100%;
    transform: scale(1);
  }
}

// Bottom Left
@keyframes scale-up-bl {
  0% {
    transform-origin: 0% 100%;
    transform: scale(0.5);
  }

  100% {
    transform-origin: 0% 100%;
    transform: scale(1);
  }
}

// Left
@keyframes scale-up-left {
  0% {
    transform-origin: 0% 50%;
    transform: scale(0.5);
  }

  100% {
    transform-origin: 0% 50%;
    transform: scale(1);
  }
}

// Top Left
@keyframes scale-up-tl {
  0% {
    transform-origin: 0% 0%;
    transform: scale(0.5);
  }

  100% {
    transform-origin: 0% 0%;
    transform: scale(1);
  }
}

// Horizontal Center
@keyframes scale-up-hor-center {
  0% {
    transform: scaleX(0.4);
  }

  100% {
    transform: scaleX(1);
  }
}

// Horizontal Left
@keyframes scale-up-hor-left {
  0% {
    transform-origin: 0% 0%;
    transform: scaleX(0.4);
  }

  100% {
    transform-origin: 0% 0%;
    transform: scaleX(1);
  }
}

// Horizontal Right
@keyframes scale-up-hor-right {
  0% {
    transform-origin: 100% 100%;
    transform: scaleX(0.4);
  }

  100% {
    transform-origin: 100% 100%;
    transform: scaleX(1);
  }
}

// Vertical Center
@keyframes scale-up-ver-center {
  0% {
    transform: scaleY(0.4);
  }

  100% {
    transform: scaleY(1);
  }
}

// Vertical Top
@keyframes scale-up-ver-top {
  0% {
    transform-origin: 0% 0%;
    transform: scaleY(0.4);
  }

  100% {
    transform-origin: 0% 0%;
    transform: scaleY(1);
  }
}

// Vertical Bottom
@keyframes scale-up-ver-bottom {
  0% {
    transform-origin: 100% 100%;
    transform: scaleY(0.4);
  }

  100% {
    transform-origin: 100% 100%;
    transform: scaleY(1);
  }
}
</style>
